# Generated by Django 4.2.11 on 2024-05-19 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 5, 19, 3, 22, 52, 652587), verbose_name='Опубликована'),
        ),
    ]
